---
permalink: /:month-:day-:year/:title.html
auto: false 
pygments: true
baseurl: 
markdown:    maruku
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

